#!/bin/sh
# This string of tests runs router to router 
# It requires the ssh keys
# hwtest variables_file
. $1

# Capture as much relevant data as possible

capture_start() {
dmesg > $1/local.start.dmesg
$SSH $SERVER dmesg > $1/$SERVER.start.dmesg
$TC -s qdisc show dev $IFACE > $1/local.start.tc
$SSH $SERVER "$TC -s qdisc show dev $REMOTE_IFACE" > $1/$SERVER.start.tc
}

capture_end() {
dmesg > $1/local.end.dmesg
$SSH $SERVER dmesg > $1/$SERVER.end.dmesg
$TC -s qdisc show dev $IFACE > $1/local.end.tc
$SSH $SERVER "$TC -s qdisc show dev $REMOTE_IFACE" > $1/$SERVER.end.tc
}

# Various and sundry things can go wrong

reset_stuff() {
$SSH $SERVER IFACE=$REMOTE_IFACE qlen_bk=128 qlen_be=128 qlen_vi=128 qlen_vo=128 QMODEL=codel $DEBLOAT
$SSH $SERVER "$KILLALL netserver; $KILLALL -1 xinetd; $IFCONFIG $REMOTE_IFACE txqueuelen 1000; $TC qdisc del dev $REMOTE_IFACE root"
ifconfig $IFACE txqueuelen 1000
qlen_bk=128 qlen_be=128 qlen_vi=128 qlen_vo=128 QMODEL=codel $DEBLOAT
$TC qdisc del dev $IFACE root 2> /dev/null
}

test4() {
LOGS=/tmp/$1/4_QUEUE/
mkdir -p $LOGS 2> /dev/null
$1
capture_start $LOGS
$PING > ${LOGS}ping.log &
sleep 5
netperf -l$DUR -Y "CS1,CS1"-H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}bk.log &
netperf -l$DUR -Y "BE,BE" -H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}be.log &
netperf -l$DUR -Y "CS6,CS6" -H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}vi.log &
netperf -l$DUR -Y "EF,EF" -H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}ef.log &
sleep $DUR
killall fping
capture_end $LOGS
echo $1:4QUEUE:throughput:`cat ${LOGS}[bve]*.log | awk '{ SUM += $5} END { print SUM}'`
echo $1:4QUEUE:ping_latency:`tail -2 ${LOGS}ping*.log | head -1`
}

testBE() {
LOGS=/tmp/$1/BE_QUEUE/
mkdir -p $LOGS 2> /dev/null
$1
capture_start $LOGS
$PING > ${LOGS}ping.log &
sleep 5
netperf -l$DUR -Y "BE,BE" -H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}be.log &
sleep $DUR
killall fping
capture_end $LOGS
echo $1:BE:throughput:`cat ${LOGS}be*.log | awk '{ SUM += $5} END { print SUM}'`
echo $1:BE:ping_latency:`tail -2 ${LOGS}ping*.log | head -1`
}

testBE4() {
LOGS=/tmp/$1/BE_QUEUE4/
mkdir -p $LOGS 2> /dev/null
$1
capture_end $LOGS
$PING > ${LOGS}ping.log &
sleep 5
netperf -l$DUR -Y "BE,BE" -H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}be1.log &
netperf -l$DUR -Y "BE,BE" -H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}be2.log &
netperf -l$DUR -Y "BE,BE" -H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}be3.log &
netperf -l$DUR -Y "BE,BE" -H $SERVER $NETPERF_TEST | tail -1 > ${LOGS}be4.log &
sleep $DUR
killall fping
capture_end $LOGS
echo $1:BE4:throughput:`cat ${LOGS}be*.log | awk '{ SUM += $5} END { print SUM}'`
echo $1:BE4:ping_latency:`tail -2 ${LOGS}ping*.log | head -1`
}

# Thse are the defaults 
pfifo_1000_hw128() {
:
}

pfifo_30_hw128() {
$IFCONFIG $IFACE txqueuelen 30
$SSH $SERVER $IFCONFIG $REMOTE_IFACE txqueuelen 30
}

pfifo_30_hw2() {
$IFCONFIG $IFACE txqueuelen 30
$SSH $SERVER $IFCONFIG $REMOTE_IFACE txqueuelen 30
qlen_bk=2 qlen_be=2 qlen_vi=2 qlen_vo=2 QMODEL=codel $DEBLOAT
$SSH $SERVER IFACE=$REMOTE_IFACE qlen_bk=2 qlen_be=2 qlen_vi=2 qlen_vo=2 QMODEL=codel $DEBLOAT
$TC qdisc del dev $IFACE root
$SSH $SERVER $TC qdisc del dev $REMOTE_IFACE root
}

codel() {
$IFCONFIG $IFACE txqueuelen 1000
$SSH $SERVER $IFCONFIG $REMOTE_IFACE txqueuelen 1000
}

fq_codel_ll_hw128() {
qlen_bk=128 qlen_be=128 qlen_vi=128 qlen_vo=128 QMODEL=fq_codel_ll $DEBLOAT
$SSH $SERVER IFACE=$REMOTE_IFACE qlen_bk=128 qlen_be=128 qlen_vi=128 qlen_vo=128 QMODEL=fq_codel_ll $DEBLOAT
}

fq_codel_ll_hw2() {
qlen_bk=2 qlen_be=2 qlen_vi=2 qlen_vo=2 QMODEL=fq_codel_ll $DEBLOAT
$SSH $SERVER IFACE=$REMOTE_IFACE qlen_bk=2 qlen_be=2 qlen_vi=2 qlen_vo=2 QMODEL=fq_codel_ll $DEBLOAT
}

fq_codel_ll_hw3() {
qlen_bk=3 qlen_be=3 qlen_vi=3 qlen_vo=2 QMODEL=fq_codel_ll $DEBLOAT
$SSH $SERVER IFACE=$REMOTE_IFACE qlen_bk=2 qlen_be=2 qlen_vi=2 qlen_vo=2 QMODEL=fq_codel_ll $DEBLOAT
}

fq_codel_ll_hw3_quantum_1514() {
CODEL_LL_QUANTUM=1514 qlen_bk=3 qlen_be=3 qlen_vi=3 qlen_vo=2 QMODEL=fq_codel_ll $DEBLOAT
$SSH $SERVER CODEL_LL_QUANTUM=1514 IFACE=$REMOTE_IFACE qlen_bk=2 qlen_be=2 qlen_vi=2 qlen_vo=2 QMODEL=fq_codel_ll $DEBLOAT
}

fq_codel_ll_hw2_quantum_1514() {
CODEL_LL_QUANTUM=1514 qlen_bk=2 qlen_be=2 qlen_vi=2 qlen_vo=2 QMODEL=fq_codel_ll $DEBLOAT
$SSH $SERVER CODEL_LL_QUANTUM=1514 IFACE=$REMOTE_IFACE qlen_bk=2 qlen_be=2 qlen_vi=2 qlen_vo=2 QMODEL=fq_codel_ll $DEBLOAT
}

for i in $TESTS
do
	for q in $QUEUE_SETUP
	do
	reset_stuff
	$i $q
	sleep 60
	done
done	


